# Generated by Django 3.1.4 on 2023-05-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=10)),
                ('full_name', models.CharField(default='test', max_length=50)),
                ('description', models.CharField(default='test', max_length=255)),
                ('logo', models.ImageField(default='test', upload_to='party_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('cnic', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('family_no', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'unique_together': {('cnic', 'family_no')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='ai_evm.party')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='by', to='ai_evm.voter')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai_evm.voter'),
        ),
    ]
