# Generated by Django 3.1.4 on 2023-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_evm', '0003_remove_voter_isnominee'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='description',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='logo',
            field=models.ImageField(default='test', upload_to='party_logos/'),
        ),
        migrations.AlterField(
            model_name='party',
            name='full_name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
